<?php

namespace App\Command;

use App\Broker\SensorManager;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputArgument;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;
use Symfony\Contracts\HttpClient\HttpClientInterface;

class NgsiLdEntityCreate extends Command
{
    protected static $defaultName = 'test:ngsi-ld:entity:create';

    /** @var HttpClientInterface */
    private $sensorManager;

    public function __construct(SensorManager $sensorManager)
    {
        parent::__construct();
        $this->sensorManager = $sensorManager;
    }

    protected function configure()
    {
        $this->addArgument('id', InputArgument::REQUIRED, 'The id');
    }

    protected function execute(InputInterface $input, OutputInterface $output)
    {
        $id = $input->getArgument('id');

//        $this->sensorManager
        parent::execute($input, $output); // TODO: Change the autogenerated stub
    }
}
