<?php

namespace App\Scorpio;

use App\Entity\Sensor;
use App\Repository\SensorRepository;
use App\Traits\LoggerTrait;
use Doctrine\ORM\EntityManagerInterface;
use Exception;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\OptionsResolver\OptionsResolver;

class SensorManager
{
    use LoggerTrait;

    /** @var Client */
    private $client;

    /** @var EntityManagerInterface */
    private $entityManager;

    /** @var array */
    private $options;

    public function __construct(Client $client, SensorRepository $sensorRepository, EntityManagerInterface $entityManager, array $sensorManagerOptions)
    {
        $this->client = $client;
        $this->entityManager = $entityManager;

        $resolver = new OptionsResolver();

        $this->options = $resolver->resolve($sensorManagerOptions);
    }

    public function search(array $options = []): array
    {
        $pattern = $options['query']['q'] ?? $options['query']['query'] ?? null;
        $result = [];
        foreach ([Client::ENTITY_TYPE_SENSOR] as $type) {
            $brokerQuery = [
                'type' => $type,
                'idPattern' => $pattern,
            ];
            try {
                // @see https://www.etsi.org/deliver/etsi_gs/CIM/001_099/009/01.01.01_60/gs_CIM009v010101p.pdf
                $response = $this->client->getEntities($brokerQuery);
                $items = array_filter($response->toArray());
                if (!empty($items)) {
                    $result[] = $items;
                }
            } catch (Exception $e) {
            }
        }

        if (!empty($result)) {
            // Flatten.
            $result = array_merge(...$result);
            // Index by id (to remove duplicates).
            $result = array_column($result, null, 'id');

            if (isset($options['mission_sensors'])) {
                $missionSensors = $options['mission_sensors'];
                foreach ($result as $id => &$item) {
                    $item['_metadata']['mission_sensor'] = $missionSensors[$id] ?? null;
                }
            }
        }

        return [
            'options' => $options,
            'data' => array_values($result),
        ];
    }

    public function getSensors(array $criteria = [])
    {
        return $this->getRepository()->findBy($criteria);
    }

    public function getSensor(string $id)
    {
        $sensor = $this->getRepository()->find($id);

        if (null === $sensor) {
            $data = $this->client->getEntity($id);
            if (Client::ENTITY_TYPE_SENSOR === ($data['type'] ?? null)) {
                // Get stream generated by the sensor.
                $response = $this->client->getEntities([
                    'type' => Client::ENTITY_TYPE_STREAM,
                    'q' => sprintf('%s==%s', Client::ENTITY_ATTRIBUTE_GENERATED_BY, $data['id']),
                ]);
                if (Response::HTTP_OK === $response->getStatusCode()) {
                    $streams = $response->toArray();
                    if (1 !== count($streams)) {
                        throw new \RuntimeException(sprintf('Cannot get stream for sensor %s', $data['id']));
                    }
                    $stream = reset($streams);
                    // Get stream observation.
                    $response = $this->client->getEntities([
                        'type' => Client::ENTITY_TYPE_STREAM_OBSERVATION,
                        'q' => sprintf('%s==%s', Client::ENTITY_ATTRIBUTE_BELONGS_TO, $stream['id']),
                    ]);
                    if (Response::HTTP_OK === $response->getStatusCode()) {
                        $observations = $response->toArray();
                        if (1 !== count($observations)) {
                            throw new \RuntimeException(sprintf('Cannot get observation for stream %s', $stream['id']));
                        }
                        $observation = reset($observations);

                        $sensor = (new Sensor())
                            ->setId($id)
                            ->setData($data)
                            ->setStream($stream)
                            ->setStreamObservation($observation);
                        $this->entityManager->persist($sensor);
                        $this->entityManager->flush();
                    }
                }
            }
        }

        if (null === $sensor) {
            throw new \RuntimeException(sprintf('Invalid sensor id: %s', $id));
        }

        return $sensor;
    }

    public function updateSensors()
    {
        $repository = $this->getRepository();
        foreach ($this->options['types'] as $type) {
            $query = ['type' => $type];
            $response = $this->client->getEntities($query);
            if (Response::HTTP_OK === $response->getStatusCode()) {
                $result = $response->toArray();
                foreach ($result as $data) {
                    if (isset($data['id'])) {
                        $id = $data['id'];
                        $sensor = $repository->find($data['id']);
                        if (null === $sensor) {
                            $sensor = (new Sensor())
                                ->setId($id);
                        }
                        $sensor
                            ->setData($data);
                        $this->entityManager->persist($sensor);
                        $sensors[] = $sensor;
                    }
                }
                $this->entityManager->flush();
            }
        }
    }

    private function getRepository(): SensorRepository
    {
        return $this->entityManager->getRepository(Sensor::class);
    }
}
